[package]
name = "nemo-metamorphic-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
nemo = { path = "../nemo/nemo" }
nemo-cli = { path = "../nemo/nemo-cli" }
petgraph = "0.8.3"
rand = "0.9.2"
rand_chacha = "0.9.0"

